add ipv6 support
new ipv6 support, new menu for ip v4 and v6 protocol

diff --git a/lxd-forward b/lxd-forward
--- a/lxd-forward
+++ b/lxd-forward
@@ -8,15 +8,23 @@
 # the main idea was found on ugle-z.no, I got this ideia and improve show to show and organizations to turn human experienci better
 
 cmd=$1
-container_name=$2
-container_port=$3
-host_port=$4
+version=$2
+container_name=$3
+container_port=$4
+host_port=$5
 
 function usage() {
   echo "Usage: $(basename ${0})
   list
-  add [container] [port] [host port]
-  delete [rule_number]"
+  add [ip_version v4/v6] [container] [port] [host port]
+  del [ip_version v4/v6] [rule_number]
+
+  Example:
+  list
+  add v4 ubuntu 80 80
+  add v6 ubuntu 80 80
+  del v4 1
+  del v6 1"
   exit 1
 }
 
@@ -28,15 +36,17 @@ function error() {
 test -n "$cmd" || usage
 
 function list() {
-  echo "----------------------------------------------------------------------------------------------------"
-  printf "|\tRule\t|\tConteiner\t|\tIP\t\t|  Host port\t|   Container port |\n"
-  echo "----------------------------------------------------------------------------------------------------"
+  echo "----------------------------------------------------------------------------------------------------------------------------"
+  printf "|\tRule\t|\tConteiner\t|\tIP\t\t\t\t\t|  Host port\t|   Container port |\n"
+  echo "----------------------------------------------------------------------------------------------------------------------------"
 
-  containers=$(lxc list | grep RUNNING | awk '{print $2, $6}')
+  containers=$(lxc list | grep RUNNING | awk '{print $2, $6, $9}')
   echo "${containers}" | while read line; do
     c_name=$(echo $line | awk '{print $1}')
     c_ip=$(echo $line | awk '{print $2}')
+    c_ip6=$(echo $line | awk '{print $3}')
     forwarded_ports=$(iptables -t nat --line-numbers -L --numeric | grep $c_ip)
+    forwarded_ports6=$(ip6tables -t nat --line-numbers -L --numeric | grep $c_ip6)
     echo "$forwarded_ports" | while IFS= read -r ports_line; do
       rule_no=$(echo $ports_line | awk '{print $1}')
       host_port=$(echo $ports_line | awk '{print $8}')
@@ -44,18 +54,39 @@ function list() {
       container=$(echo $ports_line | awk '{print $9}')
       container=$(echo $container | awk -F\: '{print $3}')
       if [ "${rule_no}" != "" ]; then
-        printf "|\t${rule_no}\t|\t${c_name}\t|\t${c_ip}\t|\t${host_port}\t|\t${container}\t   |\n"
-        echo "----------------------------------------------------------------------------------------------------"
+        printf "|\t${rule_no} v4\t|\t${c_name}\t|\t${c_ip}\t\t\t\t|\t${host_port}\t|\t${container}\t   |\n"
       fi
     done
-  done
+    echo "$forwarded_ports6" | while IFS= read -r ports_line; do
+      rule_no=$(echo $ports_line | awk '{print $1}')
+      host_port=$(echo $ports_line | awk '{print $7}')
+      host_port=$(echo $host_port | awk -F\: '{print $2}')
+      container=$(echo $ports_line | awk '{print $8}')
+      container=$(echo $container | awk -F\]\: '{print $2}')
+      if [ "${rule_no}" != "" ]; then
+        printf "|\t${rule_no} v6\t|\t${c_name}\t|\t${c_ip6}\t|\t${host_port}\t|\t${container}\t   |\n"
+      fi
+    done
+    echo "----------------------------------------------------------------------------------------------------------------------------"
+done
+}
+
+function add() {
+case "$version" in
+  "v4") forward $container_name $container_port $host_port
+  ;;
+  "v6") forward6 $container_name $container_port $host_port
+  ;;
+  *) usage
+  ;;
+esac
 }
 
 function forward() {
   c_name=$1
   c_port=$2
   h_port=$3
-  container_info=$(lxc list $c_name | grep RUNNING | awk '{print $2, $6}' | grep $c_name)
+  container_info=$(lxc list $c_name | grep RUNNING | awk '{print $2, $6, $9}' | grep $c_name)
   ip=$(echo -n $container_info | awk '{printf("%s",$2)}')
   test -n "$ip" || error "Container not found or not assigned an IP address"
   test -n "$c_port" || error "Container port not specified"
@@ -64,18 +95,48 @@ function forward() {
   iptables -t nat -A PREROUTING -p tcp --dport "$h_port" -j DNAT --to-destination "${ip}:${c_port}"
 }
 
+function forward6() {
+  c_name=$1
+  c_port=$2
+  h_port=$3
+  container_info=$(lxc list $c_name | grep RUNNING | awk '{print $2, $6, $9}' | grep $c_name)
+  ip6=$(echo -n $container_info | awk '{printf("%s",$3)}')
+  test -n "$ip6" || error "Container not found or not assigned an IP6 address"
+  test -n "$c_port" || error "Container port not specified"
+  test -n "$h_port" || h_port=$c_port
+
+  ip6tables -t nat -A PREROUTING -p tcp --dport "$h_port" -j DNAT --to-destination "[${ip6}]":"${c_port}"
+}
+
+function del() {
+case "$version" in
+  "v4") delete $2
+  ;;
+  "v6") delete6 $2
+  ;;
+  *) usage
+  ;;
+esac
+}
+
 function delete() {
   rule_no=$1
   test -n "$rule_no" || error "Must specify rule no."
   iptables -t nat -D PREROUTING "${rule_no}"
 }
 
+function delete6() {
+  rule_no=$1
+  test -n "$rule_no" || error "Must specify rule no."
+  ip6tables -t nat -D PREROUTING "${rule_no}"
+}
+
 case "$cmd" in
   "list") list
   ;;
-  "add") forward $container_name $container_port $host_port
+  "add") add $version
   ;;
-  "delete") delete $2 # Rule no.
+  "del") del $version $3 # Rule no.
   ;;
   *) usage
   ;;
